import Footer from '@/components/Footer'
import type { Metadata } from 'next'
import ToolNav from '@/components/ToolNav'
import XmlFormatterClient from './XmlFormatterClient'
import AdSlot from '@/components/AdSlot'

export const metadata: Metadata = {
  title: 'XML Formatter & Beautifier — Format XML Online | FormatMyJSON',
  description: 'Free online XML formatter and beautifier. Paste your XML to instantly format, validate, and beautify with proper indentation. No sign-up required.',
  alternates: { canonical: 'https://formatmyjson.com/xml-formatter' },
}

const faqs = [
  { q: 'What is XML formatting?', a: 'XML formatting transforms compact or minified XML into a human-readable structure with consistent indentation and line breaks. Formatted XML makes it significantly easier to trace element nesting, spot mismatched tags, and understand the overall document hierarchy without relying on external tooling.' },
  { q: 'Can I validate XML with this tool?', a: 'Yes. The tool automatically checks your XML for well-formedness as you paste it. If a tag is unclosed, an attribute is malformed, or the document violates XML syntax rules, an error message is displayed with details about what went wrong and where.' },
  { q: 'Does this tool work offline?', a: 'All processing happens entirely in your browser using client-side JavaScript. Your XML data is never sent to a server, which means the tool works even without an active internet connection once the page has loaded, and your data stays completely private.' },
  { q: 'What indent sizes are supported?', a: 'You can choose between 2-space, 4-space, and tab indentation. The default is 2 spaces, which is the most common convention for XML files. Changing the indent size re-formats the entire document instantly.' },
  { q: 'Is there a size limit for XML input?', a: 'There is no hard limit imposed by the tool. However, because formatting runs in your browser, very large files (over 5-10 MB) may cause brief lag depending on your device. For typical XML payloads used in APIs and configuration files, performance is instantaneous.' },
  { q: 'How does this differ from an XML validator?', a: 'An XML formatter focuses on presentation: it adds indentation and line breaks to make the document readable. An XML validator checks whether the document conforms to a schema (DTD or XSD). This tool primarily formats, but it also catches well-formedness errors such as unclosed tags and illegal characters.' },
  { q: 'Can I minify XML instead of beautifying it?', a: 'The primary purpose of this tool is beautification, but you can achieve minification by copying the formatted output and removing whitespace with a text editor. Some XML tools on this site may support a minify toggle in the future.' },
  { q: 'What XML declarations are preserved?', a: 'The XML declaration (<?xml version="1.0" encoding="UTF-8"?>) and processing instructions are preserved in the formatted output. CDATA sections, comments, and DOCTYPE declarations are also maintained.' },
]

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map(f => ({
    '@type': 'Question',
    name: f.q,
    acceptedAnswer: { '@type': 'Answer', text: f.a },
  })),
}

export default function XmlFormatterPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <div className="min-h-screen bg-zinc-950">
        <header className="border-b border-zinc-800 px-4 py-4">
          <div className="max-w-5xl mx-auto">
            <div className="text-lg font-bold text-white">{'{ }'} JSON Formatter</div>
          </div>
        </header>
        <main className="max-w-6xl mx-auto px-4 py-8">
          <ToolNav />
          <div className="mb-6 text-center">
            <h1 className="text-3xl font-bold text-white mb-2">XML Formatter & Beautifier</h1>
            <p className="text-zinc-400 text-sm">Paste your XML to instantly format, beautify, and validate. 100% client-side.</p>
          </div>
          <XmlFormatterClient />
          <article className="mt-16 space-y-8">
            <section>
              <h2 className="text-2xl font-bold text-white mb-3">What is XML Formatting and Why Does It Matter?</h2>
              <p className="text-zinc-400 leading-relaxed mb-3">
                XML (eXtensible Markup Language) is a cornerstone of data exchange across web services, enterprise applications, and configuration management. When XML documents are transmitted over networks or generated by machines, they are often compressed into a single line to reduce payload size. While efficient for transport, this minified format is nearly impossible for humans to read or debug.
              </p>
              <p className="text-zinc-400 leading-relaxed">
                XML formatting (also called XML beautification or pretty-printing) adds consistent indentation, line breaks, and spacing to an XML document so that its hierarchical structure becomes immediately visible. Each nested element is indented one level deeper than its parent, making it trivial to trace relationships between elements and identify where a particular branch of the tree starts and ends.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-3">Common Use Cases for XML Formatting</h2>
              <p className="text-zinc-400 leading-relaxed mb-3">
                Developers and system administrators encounter XML in many contexts. SOAP web services return XML responses that often arrive as a single dense string. Configuration files for tools like Apache Maven (pom.xml), Android manifests, and .NET application configs use XML extensively. SVG graphics are XML documents under the hood, and many legacy enterprise systems rely on XML-based message queues.
              </p>
              <p className="text-zinc-400 leading-relaxed">
                In all of these scenarios, being able to quickly format and inspect XML is essential for troubleshooting. A properly formatted document lets you verify that the correct elements and attributes are present, compare two versions of a document side by side, and paste structured data into documentation or issue trackers where readability matters.
              </p>
            </section>

            <AdSlot slot="8036801172" format="article" />

            <section>
              <h2 className="text-2xl font-bold text-white mb-3">How This XML Formatter Works</h2>
              <p className="text-zinc-400 leading-relaxed mb-3">
                This tool parses your XML input using the browser's built-in DOMParser API, which is the same parser used by modern web browsers to render web pages. The parser reads the entire document, builds an in-memory tree, and then serializes it back to a string with the indentation level you have selected. Because parsing happens natively in the browser engine, it is both fast and reliable.
              </p>
              <p className="text-zinc-400 leading-relaxed">
                If the input contains syntax errors — such as a missing closing tag, an unescaped ampersand, or an attribute without quotes — the parser returns an error document instead of a formatted result. The tool detects this and surfaces a clear error message so you can fix the problem before retrying. This makes it a lightweight validator as well as a formatter.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-3">Tips for Working with XML</h2>
              <p className="text-zinc-400 leading-relaxed mb-3">
                Always declare the encoding at the top of your XML document using the XML declaration (for example, version 1.0 with UTF-8 encoding). This prevents character encoding issues when your document contains non-ASCII characters. When embedding special characters in element content, use XML entities: &amp;amp; for ampersand, &amp;lt; for less-than, and &amp;gt; for greater-than.
              </p>
              <p className="text-zinc-400 leading-relaxed">
                For documents that contain large blocks of text with many special characters, consider using CDATA sections instead of escaping each character individually. CDATA sections tell the parser to treat everything inside as literal text, which is cleaner and easier to maintain. This tool preserves CDATA sections during formatting so they remain intact in the output.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-3">Frequently Asked Questions</h2>
              <div className="space-y-6">
                {faqs.map(faq => (
                  <div key={faq.q}>
                    <h3 className="text-lg font-semibold text-zinc-200">{faq.q}</h3>
                    <p className="text-zinc-400 leading-relaxed mt-1">{faq.a}</p>
                  </div>
                ))}
              </div>
            </section>
          </article>
        </main>
        <Footer />
      </div>
    </>
  )
}
